server:
  port: 10010
  servlet:
    context-path: /hashtags/
spring:
  application:
    name: techmojo-TwitterHashtags-api
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    username: root
    password: secret
    driverClassName: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    generte-ddl : false
    hibernate:
      ddl-auto: none
    show_sql: true
    database-platform : org.hibernate.dialect.MySQL5Dialect