CREATE TABLE IF NOT EXISTS hashtag_repo
(
   id BIGINT(20) NOT NULL AUTO_INCREMENT,
   hashtag VARCHAR(255) NOT NULL,
   count BIGINT(20) NOT NULL DEFAULT 1,
   PRIMARY KEY (id),
   UNIQUE INDEX HASHTAG_UNIQUE_KEY (hashtag)
);